name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install Build Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja git curl zip unzip tar

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DBUILD_TESTS=TRUE

      - name: Build
        run: |
          cd build
          cmake --build . --config Release
