name: OSX

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: cmake . -DCMAKE_CXX_COMPILER=g++-11

      - name: Build
        run: cmake --build . --config Release
