name: OSX

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=g++-11 -DBUILD_TESTS=TRUE

      - name: Build
        run: |
          cd build
          cmake --build . --config Release
