name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: cmake . -G Ninja -DCMAKE_CXX_COMPILER:FILEPATH="C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/ENTERPRISE/VC/Tools/Llvm/x64/bin/clang.exe" -DCMAKE_MAKE_PROGRAM="C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/ENTERPRISE/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/CMAKE/Ninja/ninja.exe"

      - name: Build
        run: cmake --build . --config Release
